export enum NODE_TYPE {
  TOKEN = 'TOKEN',
  IDENTIFIER = 'IDENTIFIER',
  BOOLEAN_LITERAL = 'BOOLEAN_LITERAL',
  SINGLE_EXPRESSION = 'SINGLE_EXPRESSION',
  VARIABLE_MODIFIER = 'VARIABLE_MODIFIER',
  VARIABLE_DECLARATOR = 'VARIABLE_DECLARATOR',
  VARIABLE_STATEMENT = 'VARIABLE_STATEMENT',
}
