export const SPACE = ' '
export const NEW_LINE = '\n'

// keywords
export const LET = 'let'
export const CONST = 'const'
export const BREAK = 'break'
export const CONTINUE = 'continue'
export const IF = 'if'
export const ELSE = 'else'
export const WHILE = 'while'
export const FUNCTION = 'function'
export const UNDEFINED = 'undefined'
export const NULL = 'null'
export const TRUE = 'true'
export const FALSE = 'false'
export const NEW = 'new'
export const CLASS = 'class'
